name: Automation Tests

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Print Branch Name
        run: echo "Hello from Target Workflow"

      - name: Print Environment Name
        run: |
          echo "Environment Value=${{ github.event.client_payload.environment }}" >> $GITHUB_ENV
          echo "Event Value=${{ github.event_name }}" >> @GITHUB_ENV
