name: Automation Tests

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch name
        run: echo "Hello from Target Workflow"

      - name: Print branch name
        run: echo "Value=${{ github.event.client_payload.unit }}" >> $GITHUB_ENV
