name: Unit Test Project

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Branch Name
        run: echo "Branch name ${GITHUB_REF_NAME}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.7.*

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        working-directory: ConsoleAppProject
        run: dotnet build --no-restore

      - name: Test        
        run: dotnet test --no-restore --no-build --verbosity normal
