name: Automation Tests

on:
  workflow_call:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch name
        run: echo "Branch name ${GITHUB_REF_NAME}"

      - name: Setup Build Version
        run: |
          echo "${{ github.run_number }}"
          echo "${{ secrets.GH_PAT }}"

      - name: Checkout AutomationTest Repository
        uses: actions/checkout@v4
        with:
          repository: vishalpatel-73/AutomationTest
          token: ${{ secrets.GH_PAT }}
          path: master

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        working-directory: TestProject
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal
